/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * GigDeploy Platform API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * @summary Login with phone and password
 */
export const LoginBody = zod.object({
  phone: zod
    .string()
    .describe(
      "E.164 phone number with spaces allowed, hyphens not allowed. e.g. +963 964 931 267",
    ),
  password: zod.string(),
});

export const LoginResponse = zod.object({
  user: zod.object({
    id: zod.number(),
    name: zod.string(),
    phone: zod.string().nullable(),
    email: zod.string().nullable(),
    role: zod.enum(["superadmin", "owner", "rep"]),
    status: zod.enum(["active", "pending_interview", "rejected"]),
    area: zod.string().nullable(),
    salesTarget: zod.number().nullable(),
    rewardBalance: zod.number(),
    createdAt: zod.string(),
  }),
});

/**
 * @summary Logout current session
 */
export const LogoutResponse = zod.object({
  success: zod.boolean(),
});

/**
 * @summary Get current authenticated user
 */
export const GetMeResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  phone: zod.string().nullable(),
  email: zod.string().nullable(),
  role: zod.enum(["superadmin", "owner", "rep"]),
  status: zod.enum(["active", "pending_interview", "rejected"]),
  area: zod.string().nullable(),
  salesTarget: zod.number().nullable(),
  rewardBalance: zod.number(),
  createdAt: zod.string(),
});

/**
 * @summary Get platform-wide settings
 */
export const GetPlatformSettingsResponse = zod.object({
  id: zod.number(),
  onboardingMode: zod.enum(["open_access", "interview_required"]),
  platformFeeRate: zod.number(),
  updatedAt: zod.string(),
});

/**
 * @summary Update platform-wide settings (superadmin only)
 */
export const UpdatePlatformSettingsBody = zod.object({
  onboardingMode: zod.enum(["open_access", "interview_required"]).optional(),
  platformFeeRate: zod.number().optional(),
});

export const UpdatePlatformSettingsResponse = zod.object({
  id: zod.number(),
  onboardingMode: zod.enum(["open_access", "interview_required"]),
  platformFeeRate: zod.number(),
  updatedAt: zod.string(),
});

/**
 * @summary List all users (owner/superadmin)
 */
export const ListUsersQueryParams = zod.object({
  role: zod.coerce.string().optional(),
});

export const ListUsersResponseItem = zod.object({
  id: zod.number(),
  name: zod.string(),
  phone: zod.string().nullable(),
  email: zod.string().nullable(),
  role: zod.enum(["superadmin", "owner", "rep"]),
  status: zod.enum(["active", "pending_interview", "rejected"]),
  area: zod.string().nullable(),
  salesTarget: zod.number().nullable(),
  rewardBalance: zod.number(),
  createdAt: zod.string(),
});
export const ListUsersResponse = zod.array(ListUsersResponseItem);

/**
 * @summary Create a new user (superadmin only — used to onboard Owners)
 */
export const CreateUserBody = zod.object({
  name: zod.string(),
  phone: zod.string(),
  password: zod.string(),
  role: zod.enum(["owner", "rep"]),
  email: zod.string().nullish(),
});

/**
 * @summary Bulk update area and/or sales target for multiple reps
 */
export const BulkUpdateRepsBody = zod.object({
  repIds: zod.array(zod.number()),
  area: zod.string().nullish(),
  salesTarget: zod.number().nullish(),
});

export const BulkUpdateRepsResponseItem = zod.object({
  id: zod.number(),
  name: zod.string(),
  phone: zod.string().nullable(),
  email: zod.string().nullable(),
  role: zod.enum(["superadmin", "owner", "rep"]),
  status: zod.enum(["active", "pending_interview", "rejected"]),
  area: zod.string().nullable(),
  salesTarget: zod.number().nullable(),
  rewardBalance: zod.number(),
  createdAt: zod.string(),
});
export const BulkUpdateRepsResponse = zod.array(BulkUpdateRepsResponseItem);

/**
 * @summary Get a user by ID
 */
export const GetUserParams = zod.object({
  id: zod.coerce.number(),
});

export const GetUserResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  phone: zod.string().nullable(),
  email: zod.string().nullable(),
  role: zod.enum(["superadmin", "owner", "rep"]),
  status: zod.enum(["active", "pending_interview", "rejected"]),
  area: zod.string().nullable(),
  salesTarget: zod.number().nullable(),
  rewardBalance: zod.number(),
  createdAt: zod.string(),
});

/**
 * @summary Update a user (area, salesTarget, etc.)
 */
export const UpdateUserParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateUserBody = zod.object({
  name: zod.string().optional(),
  area: zod.string().nullish(),
  salesTarget: zod.number().nullish(),
  status: zod.enum(["active", "pending_interview", "rejected"]).optional(),
});

export const UpdateUserResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  phone: zod.string().nullable(),
  email: zod.string().nullable(),
  role: zod.enum(["superadmin", "owner", "rep"]),
  status: zod.enum(["active", "pending_interview", "rejected"]),
  area: zod.string().nullable(),
  salesTarget: zod.number().nullable(),
  rewardBalance: zod.number(),
  createdAt: zod.string(),
});

/**
 * @summary Delete a user (superadmin only)
 */
export const DeleteUserParams = zod.object({
  id: zod.coerce.number(),
});

/**
 * @summary Accept a rep who is pending interview
 */
export const AcceptRepParams = zod.object({
  id: zod.coerce.number(),
});

export const AcceptRepResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  phone: zod.string().nullable(),
  email: zod.string().nullable(),
  role: zod.enum(["superadmin", "owner", "rep"]),
  status: zod.enum(["active", "pending_interview", "rejected"]),
  area: zod.string().nullable(),
  salesTarget: zod.number().nullable(),
  rewardBalance: zod.number(),
  createdAt: zod.string(),
});

/**
 * @summary List all SaaS products
 */
export const ListProductsResponseItem = zod.object({
  id: zod.number(),
  ownerId: zod.number(),
  name: zod.string(),
  description: zod.string(),
  prerequisites: zod.string(),
  rewardStructure: zod.enum(["per_subscription", "per_lead"]),
  subscriptionPrice: zod.number(),
  commissionRate: zod.number(),
  leadBounty: zod.number().nullable(),
  platformFeeRate: zod.number(),
  ownerName: zod.string().nullable(),
  questionCount: zod.number(),
  createdAt: zod.string(),
});
export const ListProductsResponse = zod.array(ListProductsResponseItem);

/**
 * @summary Create a new SaaS product (owner only)
 */
export const CreateProductBody = zod.object({
  name: zod.string(),
  description: zod.string(),
  prerequisites: zod.string(),
  rewardStructure: zod.enum(["per_subscription", "per_lead"]),
  subscriptionPrice: zod.number(),
  commissionRate: zod.number(),
  leadBounty: zod.number().nullish(),
  platformFeeRate: zod.number().optional(),
});

/**
 * @summary Get a product by ID
 */
export const GetProductParams = zod.object({
  id: zod.coerce.number(),
});

export const GetProductResponse = zod.object({
  id: zod.number(),
  ownerId: zod.number(),
  name: zod.string(),
  description: zod.string(),
  prerequisites: zod.string(),
  rewardStructure: zod.enum(["per_subscription", "per_lead"]),
  subscriptionPrice: zod.number(),
  commissionRate: zod.number(),
  leadBounty: zod.number().nullable(),
  platformFeeRate: zod.number(),
  ownerName: zod.string().nullable(),
  questionCount: zod.number(),
  createdAt: zod.string(),
});

/**
 * @summary Update a product
 */
export const UpdateProductParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateProductBody = zod.object({
  name: zod.string().optional(),
  description: zod.string().optional(),
  prerequisites: zod.string().optional(),
  rewardStructure: zod.enum(["per_subscription", "per_lead"]).optional(),
  subscriptionPrice: zod.number().optional(),
  commissionRate: zod.number().optional(),
  leadBounty: zod.number().nullish(),
  platformFeeRate: zod.number().optional(),
});

export const UpdateProductResponse = zod.object({
  id: zod.number(),
  ownerId: zod.number(),
  name: zod.string(),
  description: zod.string(),
  prerequisites: zod.string(),
  rewardStructure: zod.enum(["per_subscription", "per_lead"]),
  subscriptionPrice: zod.number(),
  commissionRate: zod.number(),
  leadBounty: zod.number().nullable(),
  platformFeeRate: zod.number(),
  ownerName: zod.string().nullable(),
  questionCount: zod.number(),
  createdAt: zod.string(),
});

/**
 * @summary Delete a product
 */
export const DeleteProductParams = zod.object({
  id: zod.coerce.number(),
});

/**
 * @summary List quiz questions for a product
 */
export const ListQuestionsParams = zod.object({
  productId: zod.coerce.number(),
});

export const ListQuestionsResponseItem = zod.object({
  id: zod.number(),
  productId: zod.number(),
  text: zod.string(),
  options: zod.array(zod.string()),
  correctIndex: zod.number(),
  createdAt: zod.string(),
});
export const ListQuestionsResponse = zod.array(ListQuestionsResponseItem);

/**
 * @summary Add a quiz question to a product
 */
export const CreateQuestionParams = zod.object({
  productId: zod.coerce.number(),
});

export const CreateQuestionBody = zod.object({
  text: zod.string(),
  options: zod.array(zod.string()),
  correctIndex: zod.number(),
});

/**
 * @summary Delete a quiz question
 */
export const DeleteQuestionParams = zod.object({
  productId: zod.coerce.number(),
  questionId: zod.coerce.number(),
});

/**
 * @summary Submit quiz answers for a product
 */
export const SubmitQuizParams = zod.object({
  productId: zod.coerce.number(),
});

export const SubmitQuizBody = zod.object({
  answers: zod.array(
    zod.object({
      questionId: zod.number(),
      selectedIndex: zod.number(),
    }),
  ),
});

export const SubmitQuizResponse = zod.object({
  passed: zod.boolean(),
  score: zod.number(),
  total: zod.number(),
  certificationStatus: zod.enum([
    "unlocked",
    "pending_interview",
    "already_certified",
    "failed",
  ]),
});

/**
 * @summary List certifications (own for rep, all for owner/superadmin)
 */
export const ListCertificationsResponseItem = zod.object({
  id: zod.number(),
  repId: zod.number(),
  repName: zod.string(),
  productId: zod.number(),
  productName: zod.string(),
  status: zod.enum(["active", "pending_interview"]),
  score: zod.number(),
  createdAt: zod.string(),
});
export const ListCertificationsResponse = zod.array(
  ListCertificationsResponseItem,
);

/**
 * @summary List leads (own for rep, all for owner/superadmin)
 */
export const ListLeadsQueryParams = zod.object({
  status: zod.coerce.string().optional(),
});

export const ListLeadsResponseItem = zod.object({
  id: zod.number(),
  repId: zod.number(),
  repName: zod.string(),
  productId: zod.number(),
  productName: zod.string(),
  contactName: zod.string(),
  contactEmail: zod.string().nullable(),
  contactPhone: zod.string().nullable(),
  notes: zod.string().nullable(),
  status: zod.enum(["pending", "approved", "rejected"]),
  commission: zod.number().nullable(),
  platformFee: zod.number().nullable(),
  isFreeTrialLead: zod.boolean(),
  createdAt: zod.string(),
});
export const ListLeadsResponse = zod.array(ListLeadsResponseItem);

/**
 * @summary Submit a new lead (rep only)
 */
export const CreateLeadBody = zod.object({
  productId: zod.number(),
  contactName: zod.string(),
  contactEmail: zod.string().nullish(),
  contactPhone: zod.string().nullish(),
  notes: zod.string().nullish(),
});

/**
 * @summary Delete a lead (superadmin only)
 */
export const DeleteLeadParams = zod.object({
  id: zod.coerce.number(),
});

/**
 * @summary Approve a lead (owner/superadmin only)
 */
export const ApproveLeadParams = zod.object({
  id: zod.coerce.number(),
});

export const ApproveLeadBody = zod.object({
  freeTrial: zod.boolean().optional(),
});

export const ApproveLeadResponse = zod.object({
  id: zod.number(),
  repId: zod.number(),
  repName: zod.string(),
  productId: zod.number(),
  productName: zod.string(),
  contactName: zod.string(),
  contactEmail: zod.string().nullable(),
  contactPhone: zod.string().nullable(),
  notes: zod.string().nullable(),
  status: zod.enum(["pending", "approved", "rejected"]),
  commission: zod.number().nullable(),
  platformFee: zod.number().nullable(),
  isFreeTrialLead: zod.boolean(),
  createdAt: zod.string(),
});

/**
 * @summary Reject a lead (owner/superadmin only)
 */
export const RejectLeadParams = zod.object({
  id: zod.coerce.number(),
});

export const RejectLeadResponse = zod.object({
  id: zod.number(),
  repId: zod.number(),
  repName: zod.string(),
  productId: zod.number(),
  productName: zod.string(),
  contactName: zod.string(),
  contactEmail: zod.string().nullable(),
  contactPhone: zod.string().nullable(),
  notes: zod.string().nullable(),
  status: zod.enum(["pending", "approved", "rejected"]),
  commission: zod.number().nullable(),
  platformFee: zod.number().nullable(),
  isFreeTrialLead: zod.boolean(),
  createdAt: zod.string(),
});

/**
 * @summary Get dashboard summary stats for current user role
 */
export const GetDashboardSummaryResponse = zod.object({
  totalReps: zod.number(),
  pendingInterviews: zod.number(),
  totalProducts: zod.number(),
  totalLeads: zod.number(),
  pendingLeads: zod.number(),
  approvedLeads: zod.number(),
  rewardBalance: zod.number(),
  myCertifications: zod.number(),
  myPendingLeads: zod.number(),
  myApprovedLeads: zod.number(),
  onboardingMode: zod.string(),
  totalSalesVolume: zod.number(),
  totalPersonalProfit: zod.number(),
  totalPayoutsToReps: zod.number(),
  totalPlatformFees: zod.number(),
  totalLeadsGenerated: zod.number(),
});
